<a href="https://colab.research.google.com/github/Aishvarya-Balaji/AI_ML_Projects/blob/main/movieRecommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# AI based movie recommendation system for OTT

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('ratings_small.csv')
X = dataset.iloc[:, :-1].values

In [ ]:
print(X)

[[1.000e+00 3.100e+01 2.500e+00]
 [1.000e+00 1.029e+03 3.000e+00]
 [1.000e+00 1.061e+03 3.000e+00]
 ...
 [6.710e+02 6.365e+03 4.000e+00]
 [6.710e+02 6.385e+03 2.500e+00]
 [6.710e+02 6.565e+03 3.500e+00]]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test= train_test_split(X, test_size = 0.25, random_state = 0)

## Training data into user-movie ratings matrix

In [ ]:
user_ids=list(set(X_train[:,0]))
movie_ids=list(set(X_train[:,1]))

In [ ]:
no_of_users=int(max(user_ids))+1
no_of_movies=int(max(movie_ids))+1

In [ ]:
X_train_matrix=np.zeros((no_of_users,no_of_movies))
for row in X_train:
  user=int(row[0])
  movie=int(row[1])
  rating=row[2]
  X_train_matrix[user][movie]=rating

# Training the SVD model

In [ ]:
import numpy as np
X_train_matrix=X_train_matrix.astype(float)
U,sigma,Vt=np.linalg.svd(X_train_matrix,full_matrices=False)
sigma=np.diag(sigma)
predicted_matrix=np.dot(np.dot(U,sigma),Vt)

# Function for recommendation

In [ ]:
def recommend_movies(user_id, train_matrix, predicted_matrix, n=10):
    user_predictions = predicted_matrix[user_id].copy()
    already_rated = train_matrix[user_id] > 0
    user_predictions[already_rated] = -1
    recommended_movies = np.argsort(user_predictions)[-n:]
    recommended_movies = recommended_movies[::-1]
    return recommended_movies


# Getting user ID and recommendation

In [ ]:
userID=int(input("Enter your user ID : "))
print("Top 10 recommended movies for you : ",recommend_movies(userID,X_train_matrix,predicted_matrix,10))

Enter your user ID : 83
Top 10 recommended movies for you :  [  82   36  296 5060   47  920  265  919 1299   34]
